# Generated by Django 5.1.1 on 2024-10-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourancite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tableappeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname_patronymic', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('appeal_type_select', models.CharField(choices=[('Предложение', 'Предложение'), ('Заявление', 'Заявление'), ('Жалоба', 'Жалоба')], default='Предложение', max_length=20)),
                ('appeal_text', models.TextField()),
                ('agreed_to_policy1', models.BooleanField(default=False)),
            ],
        ),
    ]
