# Generated by Django 5.1.1 on 2024-10-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourancite', '0002_tableappeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_drink', models.TextField()),
                ('structure_drink', models.JSONField()),
                ('image_drink', models.ImageField(upload_to='drink_images/')),
                ('drink_type_select', models.CharField(choices=[('champagne', 'Шампанское и игристые вина'), ('beer', 'Пиво'), ('strong_drinks', 'Крепкие напитки'), ('cocktails', 'Коктейли'), ('non_alcoholic', 'Безалкагольные напики')], default='champange', max_length=50)),
            ],
        ),
    ]
