# Generated by Django 5.1.1 on 2024-10-21 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourancite', '0003_tabledrink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tabledrink',
            name='drink_type_select',
            field=models.CharField(choices=[('champagne', 'Шампанское и игристые вина'), ('beer', 'Пиво'), ('strong_drinks', 'Крепкие напитки'), ('cocktails', 'Коктейли'), ('non_alcoholic', 'Безалкагольные напитки')], default='champange', max_length=50),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restourancite.table'),
            preserve_default=False,
        ),
    ]
