# Generated by Django 5.1.1 on 2024-10-21 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourancite', '0004_table_alter_tabledrink_drink_type_select_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='restourancite.table')),
            ],
        ),
    ]
