# Generated by Django 5.1.1 on 2024-12-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourancite', '0005_tableavailableslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_rating', models.IntegerField()),
                ('service_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
