# Generated by Django 5.1.1 on 2024-12-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourancite', '0006_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='atmosphere_rating',
            field=models.IntegerField(default=3),
        ),
    ]
